if(NOT LEETCODE_PROBLEM_SOURCES)
    set(LEETCODE_PROBLEM_SOURCES "/d/code/LeetCode-in-vscode/lt" CACHE STRING "")
endif()
message(STATUS "hardcode LEETCODE_PROBLEM_SOURCES:${LEETCODE_PROBLEM_SOURCES}")
